# AD-Sale Prediction from Existing customer - Logistic Regression


####Importing Libraries

In [ ]:
import pandas as pd #useful for loading the dataset
import numpy as np #to perform array

####Choose Dataset file from Local Directory

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Ad_dataset.csv to Ad_dataset.csv


####Read Dataset And View

In [ ]:
dataset = pd.read_csv('Ad_dataset.csv')
print(dataset)

     Age  Salary  Status
0     30   23000       1
1     33   58000       0
2     36   68000       0
3     27   27000       1
4     32   38000       0
..   ...     ...     ...
834   24   18000       0
835   39   18000       0
836   40   42000       0
837   26   58000       0
838   20   76000       0

[839 rows x 3 columns]


####Summarize Dataset

In [ ]:
print(dataset.shape)
dataset=pd.DataFrame(dataset)
dataset.head(5)

(839, 3)


Age  Salary  Status
0   30   23000       1
1   33   58000       0
2   36   68000       0
3   27   27000       1
4   32   38000       0

####Segregate Dataset into X(Input/IndependentVariable) & Y(Output/DependentVariable)

In [ ]:
#X = dataset.iloc[:,:-1].values
X = dataset.iloc[:,:-1]
X

Age  Salary
0     30   23000
1     33   58000
2     36   68000
3     27   27000
4     32   38000
..   ...     ...
834   24   18000
835   39   18000
836   40   42000
837   26   58000
838   20   76000

[839 rows x 2 columns]

In [ ]:
#Y = dataset.iloc[:,-1].values
Y = dataset.iloc[:,-1]
Y

0      1
1      0
2      0
3      1
4      0
      ..
834    0
835    0
836    0
837    0
838    0
Name: Status, Length: 839, dtype: int64

####Splitting Dataset into Train & Test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

##Feature Scaling
####we scale our data to make all the features contribute equally to the result

Fit_Transform - fit method is calculating the mean and variance of each of the features present in our data

Transform - Transform method is transforming all the features using the respective mean and variance,

We want our test data to be a completely new and a surprise set for our model

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)
print(X_train_sc)

[[-0.45572515  0.54257301]
 [ 0.28382882 -1.34724236]
 [-1.34318991  1.43189788]
 ...
 [-1.19527911  1.6542291 ]
 [ 1.61502596 -1.34724236]
 [ 0.87547199 -1.68073918]]


##Traning


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

####Predicting, whether new customer with Age & Salary will Buy or Not

In [ ]:
age = int(input("Enter New Customer's Age:"))
sal = int(input("Enter New Customer's Salary:"))
newCust = [[age, sal]]
result = model.predict(sc.transform(newCust))
print (result)
if result == 1:
  print("Customer will Buy")
else:
  print("Customer won't Buy")

Enter New Customer's Age:7
Enter New Customer's Salary:'89999
[0]
Customer won't Buy


####Prediction for all Test Data

In [ ]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]

### Evaluating Model - CONFUSION MATRIX

WhatsApp Image 2022-01-14 at 8.44.56 PM-2.jpeg

**Accuracy= (TP + TN) / (TP + TN + FP + FN)**



In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)
print("Accuracy of the Model:{0}%".format(accuracy_score(y_test,y_pred)*100))

Confusion Matrix:
[[176   6]
 [  7  21]]
Accuracy of the Model:93.80952380952381%
